name: Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python virtual environment
        run: python3 -m venv venv

      - name: Activate Python virtual environment
        run: source venv/bin/activate

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: sudo pip3 install -r requirements.txt

      - name: Build and deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: EPSXcuDR4HDwg3WGfmk5gqFc
          vercel-project-id: prj_C86RrX9UdmsJM8SeG3OvJh3wjNOD
          production-branch: main
          vercel-org-id: Og7rlrLPk7eNzgXT3Eea9OFf

